name: Continous Integration Tests

# Run this workflow every time a new commit is pushed to certain branches in the repository
on: 
  push:
    branches:
      - travis_ci 

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build
  build:
    needs: setup   
    steps:
      - name: Prepare Dependancies 
        run: ./gradlew downloadDependencies downloadTestDependencies downloadLinters
        shell: bash
  lint:
    steps:
      - name: Lint 
        run: |
          ./gradlew createConfigs testClasses
          ./gradlew lint --continue
          npm ci
          npm run lint 
  component-tests:
    steps:
      - name: Component Testing 
        run: |
          ./gradlew createConfigs componentTests
          ./gradlew jacocoReport
          ./gradlew generateTypes
          npm ci
          npm run coverage
  e2e-tests:
    needs: build
    steps:
      - name: Firefox Tests 
        run: |
          cd $HOME
          LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
          curl -fsSL -o chromedriver.zip "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver.zip
          cd $TRAVIS_BUILD_DIR
          mv src/e2e/resources/test.travis-chrome.properties src/e2e/resources/test.properties
          ./gradlew createConfigs testClasses generateTypes
          npm ci
          npm run build -- --progress=false --serviceWorker=false
          ./gradlew appengineStart
          ./gradlew e2eTests
