name: Continous Integration Tests

on: 
  push:
    branches:
      - travis-ci 

jobs:
  component-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache NPM packages 
        uses: actions/cache@v2 
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Backend Dependancies 
        run: ./gradlew downloadDependencies downloadTestDependencies downloadLinters
        shell: bash
      - name: Run Backend Tests    
        run: ./gradlew createConfigs componentTests 
        shell: bash 
      - name: Check Backend Coverage 
        run: ./gradlew jacocoReport
        shell: bash 
      - name: Generate Types 
        run: ./gradlew generateTypes
        shell: bash 
      - name: Install Frontend Dependancies 
        run: npm ci 
        shell: bash 
      - name: Run Frontend Tests and check Coverage 
        run: npm run coverage 
        shell: bash
      - name: Upload to Codecov 
        run: bash <(curl -s https://codecov.io/bash)
        shell: bash 
  E2E-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache NPM packages 
        uses: actions/cache@v2 
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Backend Dependancies 
        run: ./gradlew downloadDependencies downloadTestDependencies downloadLinters
        shell: bash
      - name: Update Property File 
        run: mv $GITHUB_WORKSPACE/src/e2e/resources/test.travis.properties src/e2e/resources/test.properties
        shell: bash
      - name: Create Config Files 
        run: ./gradlew createConfigs testClasses generateTypes 
        shell: bash 
      - name: Install Frontend Dependancies
        run: npm ci 
        shell: bash 
      - name: Build Frontend Bundle 
        run: npm run build -- --progress=false --serviceWorker=false 
        shell: bash 
      - name: Start App Engine 
        run: ./gradlew appengineStart 
        shell: bash 
      - name: Start Tests 
        run: ./gradlew e2eTests 
        shell: bash 
